spring:
  application:
    name: ProducerService
  kafka:
    bootstrap-servers:
    - localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
topic:
  name: TestTopic        
